INSERT INTO blog_post
VALUES (DEFAULT, 1, 'The Cognitive Benefits of Urban Green Spaces',
        'This research-based article explores how regular exposure to parks and natural environments within cities can improve focus, reduce stress, and enhance creative thinking. Dr. Thornfield presents evidence that even brief interactions with nature in urban settings can have measurable positive effects on cognitive performance.',
        '2017-03-14'),
       (DEFAULT, 1, 'Biophilic Design: Integrating Nature into Modern Workplaces',
        'Examines how incorporating natural elements in office spaces improves employee wellbeing, productivity, and job satisfaction while reducing absenteeism and burnout.',
        '2015-07-18'),
       (DEFAULT, 1, 'The Neuroscience of Forest Bathing: Why Nature Immersion Works',
        'Explores the scientific evidence behind the Japanese practice of shinrin-yoku (forest bathing) and its measurable effects on neurological activity, stress hormones, and immune function.',
        '2025-05-22'),
       (DEFAULT, 2, 'The Renaissance of Handcrafted Fountain Pens',
        'Chronicles the revival of traditional penmaking techniques and the growing community of artisans dedicated to creating writing instruments that merge engineering precision with artistic expression.',
        '2023-01-07'),
       (DEFAULT, 2, 'Vacuum Tubes in the Digital Age: The Audiophile''s Anachronism',
        'Examines why vacuum tube technology persists in high-end audio equipment despite its obsolescence in other electronic applications, exploring both technical and aesthetic considerations.',
        '2015-07-18'),
       (DEFAULT, 2, 'The Disappearing Art of Letterpress Printing',
        'Documents the history, techniques, and contemporary practitioners of traditional letterpress printing, highlighting its tactile qualities and aesthetic value in a world of digital reproduction.',
        '2022-06-30'),
       (DEFAULT, 3, 'Digital Palates: How Flavor Databases are Revolutionizing Food Science',
        'Explores how comprehensive databases of chemical compounds in foods are enabling unprecedented analysis of flavor combinations and culinary traditions.',
        '2015-03-17'),
       (DEFAULT, 3, 'The Mathematics of Baking: Algorithms for the Perfect Pastry',
        'Examines how computational approaches to ingredient ratios, temperature control, and timing are transforming traditional baking into a precise science.',
        '2015-03-17'),
       (DEFAULT, 3, 'Personalized Nutrition: When AI Becomes Your Dietary Consultant',
        'Investigates systems that use personal biomarker data, genetic information, and machine learning to create individually tailored dietary recommendations.',
        '2015-05-08'),
       (DEFAULT, 4, 'The Digital Gold Rush: Cryptocurrency Mining in Virtual Economies',
        'Investigates how in-game currencies and resources have become valuable enough to support real-world economies, particularly in developing regions.',
        '2015-12-01'),
       (DEFAULT, 4, 'Professional Gaming Houses: Inside the World''s Top eSports Teams',
        'Provides an in-depth look at the highly structured training environments where professional gamers live and work, highlighting the routines and relationships that develop in these competitive settings.',
        '2015-07-19'),
       (DEFAULT, 4, 'Virtual Real Estate: The Market for Digital Land',
        'Examines the growing market for ownership of virtual spaces in online worlds and games, including million-dollar transactions for prime digital locations.',
        '2015-02-03'),
       (DEFAULT, 5, 'Sacred Geometry: Mathematical Principles in Religious Architecture',
        'Examines how specific mathematical ratios and geometric forms have been incorporated into sacred buildings across different faith traditions, creating spaces designed to evoke specific spiritual experiences.',
        '2015-08-27'),
       (DEFAULT, 5, 'The Language of Doorways: Threshold Symbolism in Global Architecture',
        'Analyzes how entrance designs communicate cultural values about boundaries, hospitality, protection, and transitions across different architectural traditions.',
        '2015-11-12'),
       (DEFAULT, 5, 'Domestic Sanctuaries: The Evolution of Personal Space',
        'Traces how concepts of privacy, comfort, and individual expression have shaped residential architecture throughout history and across cultures.',
        '2015-04-30');